### PR TITLE
Update_freebuoyancy_gazebo9

### PR DESCRIPTION
**Pull request by alexandrechamand**
Hi ! I updated your code with the new library of gazebo9. "gazebo/math" it's not working anymore and merge into "ignition/math", some of the physics engine went directly to the world class and some name like "GetModelCount" it's now "ModelCount". You'll see all the changes in the commit :) 

Cheers, 
Alex

### CODE REVIEW

**Comment by patrickelectric** [comment]
Hi @alexandrechamand 	thank you for your contributions, I'll try to test it before the merge.

**Comment by russkel** [comment]
Hi @alexandrechamand, did you update this patch for Gazebo 10 as well?

**Comment by alexandrechamand** [comment]
Hi there, I just updated it for Gazebo 9, I didn't test it on Gazebo 10
version, I have a look on it ASAP :)

**Comment by russkel** [comment]
Thanks for this @alexandrechamand. This is on my todo list.

**Comment by alexandrechamand** [comment]
Hello Russ, I just checked on Gazebo 10, everything is working fine :)

**Comment by russkel** [comment]
Hello @alexandrechamand. Excellent. Thanks again!

**Comment by patrickelectric** [comment]
@alexandrechamand can you rebase this PR over the last version of master branch ?

**Comment by alexandrechamand** [comment]
Just made it

**Comment by russkel** [comment]
Well that makes my job easier. :tada:

**Comment by ForrestBarnes** [comment]
This change comes in the nick of time for my team. Thank you!

**Pull request merged**
